//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREOS
    {
        public string CEDULA { get; set; }
<<<<<<< HEAD
=======

        //[StringLength(20)]
        [EmailAddress]
        [Required(ErrorMessage = "El correo electrónico es un campo requerido.")]
        [Display(Name = "Correo electrónico:")]
>>>>>>> feb0edab1c2fa66947747f71469ab0256d25475a
        public string CORREO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
