//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CORREOS
    {
        public string CEDULA { get; set; }

        [StringLength(20)]
        [EmailAddress]
        [Required(ErrorMessage = "El correo electrónico es un campo requerido.")]
        [Display(Name = "Correo electrónico:")]
        public string CORREO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
