//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRIT_ACEPTACION
    {
        public string ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string REQUERIMIENTO_ID { get; set; }
        public Nullable<int> VERSION_ID { get; set; }
    
        public virtual REQUERIMIENTOS REQUERIMIENTOS { get; set; }
    }
}
