//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANEJA
    {
        public string ROL_ID { get; set; }
        public string PERMISO_ID { get; set; }
    
        public virtual PERMISOS PERMISOS { get; set; }
    }
}
