//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_IngeGrupo2Entities2 : DbContext
    {
        public BD_IngeGrupo2Entities2()
            : base("name=BD_IngeGrupo2Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAMBIOS> CAMBIOS { get; set; }
        public virtual DbSet<CORREOS> CORREOS { get; set; }
        public virtual DbSet<CRIT_ACEPTACION> CRIT_ACEPTACION { get; set; }
        public virtual DbSet<MANEJA> MANEJA { get; set; }
        public virtual DbSet<PERMISOS> PERMISOS { get; set; }
        public virtual DbSet<PROYECTO> PROYECTO { get; set; }
        public virtual DbSet<REQUERIMIENTOS> REQUERIMIENTOS { get; set; }
        public virtual DbSet<TELEFONOS> TELEFONOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
