//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoDeInge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUERIMIENTOS()
        {
            this.CAMBIOS = new HashSet<CAMBIOS>();
            this.CRIT_ACEPTACION = new HashSet<CRIT_ACEPTACION>();
        }
    
        public string ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ESFUERZO { get; set; }
        public byte[] IMAGEN { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> PRIORIDAD { get; set; }
        public string OBSERVACIONES { get; set; }
        public string MODULO { get; set; }
        public Nullable<System.DateTime> FECHAINCIO { get; set; }
        public Nullable<System.DateTime> FECHAFINAL { get; set; }
        public string ESTADO { get; set; }
        public string ENCARGADO { get; set; }
        public string PRYCTOID { get; set; }
        public int VERSION_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMBIOS> CAMBIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRIT_ACEPTACION> CRIT_ACEPTACION { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
