CREATE TABLE USUARIOS(
	CEDULA	CHAR(10),
	NOMBRE	VARCHAR(20),
	PRIMARY KEY(CEDULA)
);

CREATE TABLE PROYECTO(
	ID			CHAR(7),
	NOMBRE		VARCHAR(70),
	DESCRIPCION	VARCHAR(200),
	FECHAINICIO	DATE,
	FECHAFINAL	DATE,
	DURACION	INT,
	PRIMARY	KEY (ID)
);

CREATE TABLE CAMBIOS(
	ID				CHAR(7),
	FECHA			DATE,
	DESCRIPCION		VARCHAR(200),
	JUSTIFICACION	VARCHAR(700),
	PRIMARY KEY (ID)
);

CREATE TABLE REQUERIMINTO(
	ID				CHAR(8),
	NOMBRE			VARCHAR(70),
	ESFUERZO		INT,
	IMAGEN			IMAGE,
	DESCRIPCION		VARCHAR(200),
	PRIORIDAD		INT,
	OBSERVACIONES	VARCHAR(700),
	MODULO			VARCHAR(70),
	FECHAINCIO		DATE,
	FECHAFINAL		DATE,
	-- A = asignado P = pendiente E = en ejecucion F = finalizado C = cerrado
	ESTADO			CHAR(1),

	PRIMARY KEY (ID),

);

CREATE TABLE PERMISOS(
	ID	CHAR(7),
	NOMBRE VARCHAR(70),
	DESCRIPCION VARCHAR(200),
	PRIMARY KEY(ID)
);